version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.18
    working_directory: ~/market/frontend
    steps:
      - checkout:
          path: ~/market
      - node/install:
          install-yarn: true
          node-version: '16.18'
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run lint
          name: Run linter
      - run:
          command: yarn run test
          name: Run YARN tests

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-test:
    jobs:
      - build-and-test